[project]
name = "strava-ingestion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.4",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.3",
]
